services:
  - type: web
    name: transcribeEase
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node backend/index.js
    envVars:
      - key: API_KEY
        value: process.env.API_KEY
