services:
  - type: web
    name: transcribeEase
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node backend/index.js
    envVars:
      - key: API_KEY
        value: a87c19559f2e4921ae12b4326e11bd9e
